---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: cozy-fluxcd
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.20.4
  url: oci://ghcr.io/external-secrets/charts/external-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-secrets
    namespace: cozy-fluxcd
  install:
    remediation:
      retries: -1
    crds: Create
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    installCRDs: true
    leaderElect: true
    image:
      repository: ghcr.io/external-secrets/external-secrets
    service:
      annotations:
        lineage.cozystack.io/ignore: "true"
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      secretAnnotations:
        lineage.cozystack.io/ignore: "true"
      serviceMonitor:
        enabled: true
        interval: 1m
      service:
        annotations:
          lineage.cozystack.io/ignore: "true"
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m
      metrics:
        service:
          annotations:
            lineage.cozystack.io/ignore: "true"
    serviceMonitor:
      enabled: true
      interval: 1m
    grafanaDashboard:
      enabled: true
