---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: cozy-fluxcd
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.19.2
  url: oci://ghcr.io/external-secrets/charts/external-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-secrets
    namespace: cozy-fluxcd
  install:
    remediation:
      retries: -1
    crds: Create
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    installCRDs: true
    leaderElect: true
    image:
      repository: ghcr.io/external-secrets/external-secrets
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m
    serviceMonitor:
      enabled: true
      interval: 1m
    grafanaDashboard:
      enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
  namespace: external-secrets
type: Opaque
stringData:
  clientId: ENC[AES256_GCM,data:Bp0K0gF/O4v0LdavLaJxog==,iv:jCJNUhj3mC5YRVnnQQwqyzkz8vidbDc3lvVjtumXXV0=,tag:zNDJqOqrVUnJG44XjIP1fg==,type:str]
  clientSecret: ENC[AES256_GCM,data:aOBE0LTkbfGmI6dkdSGxAyHg7FzmqTvW2PdeKA4701Ipp1RJmWUxy9i9ToGjG1JcmhHwZvSWDKACR2ufgIjXCQ==,iv:1htoMVw36W9MQJ0MrchUpbx2H8wXmUwlo7rkfuXZezs=,tag:zTeWmX8464S3LHrkpUpz1Q==,type:str]
sops:
  age:
    - recipient: age1mlzqnslh2nrf3m4ey2afp7rqq8wtmck8t3f3xwkarqpap7e9gvtshwgx2e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSGJjQzZPdzVMUHN1WFNL
        MDBXejNEOHNCVjRqaUdKekRycFhDK1hTTlRJCkdxdENQNUFDTE1oNUZmems4T2Z2
        LzdRa1RRelgzVWh3cGsvSjdGMjRoRlUKLS0tIGRtU3B0R0pGcVpTTkJnTXRmbkdp
        Y0Q3SFA1UURoSWVuTk9kamw0Ui8rencKzWwphdc8lt8VTx2ZaWd0y/kx3ajDi6bE
        zoOtm+Exn+IwpfSAJ588+TL7D7WL+AG+vhgoat0DzWTu4/xE0ThJnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-26T15:57:13Z"
  mac: ENC[AES256_GCM,data:aCZ2SErasVXh6/ak5aERF4qB85Qt2CLQt6frqWedC5QKAdQJHjtEm5uec6nZH4GoxaA10jvAgNR+qU3EhvbN5QwberZzJEV7Y+TJqpgrXn7PP/KShXA4EePlaftJbSiJWHzTYQpJP0TC4wVUWxjLbufLhm8idUbdfOZRBSr6Nqk=,iv:J+sjutiND3Xdb8U2xGIvQt8ZltYlTSjXCEPrf0SmFc8=,tag:hreVwT/Gf5qD3YgZ3xgSPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
