---
# Namespace for Cloudflare DDNS
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-ddns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/instance: cloudflare-ddns
---
# ExternalSecret to fetch the Cloudflare API token from external secret store
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-cloudflare-api-token
  namespace: cloudflare-ddns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/instance: cloudflare-ddns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-api-token
  data:
    - secretKey: apiToken
      remoteRef:
        key: /CLOUDFLARE/API_TOKEN
---
# OCIRepository for TrueCharts (OCI)
#apiVersion: source.toolkit.fluxcd.io/v1
#kind: OCIRepository
#metadata:
#  name: truecharts-cloudflareddns
#  namespace: cozy-fluxcd
#spec:
#  interval: 1h
#  url: oci://oci.trueforge.org/truecharts/cloudflareddns
#  ref:
#    semver: ">= 12.3.5"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: truecharts
  namespace: cozy-fluxcd
spec:
  type: oci
  interval: 5m
  url: oci://tccr.io/truecharts
---
# HelmRelease for Cloudflare DDNS updater
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-dyndns
  namespace: cloudflare-ddns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/instance: cloudflare-ddns
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflareddns
      version: 12.3.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: cozy-fluxcd
  #chartRef:
  #  kind: OCIRepository
  #  name: truecharts-cloudflareddns
  #  namespace: cozy-fluxcd
  valuesFrom:
    - kind: Secret
      name: cloudflare-api-token
      valuesKey: apiToken
      targetPath: cloudflareddns.api_token
  values:
    cloudflareddns:
      interval: 300 # seconds
      detect_mode: dig-whoami.cloudflare
      detect_override: dig-google.com
      log_level: 3
      host_zone_record:
        - domain: ${DOMAIN}
          zone: ${DOMAIN}
          record: A
        - domain: "vpn.${DOMAIN}"
          zone: ${DOMAIN}
          record: A
        - domain: ${DOMAIN_OLD}
          zone: ${DOMAIN_OLD}
          record: A
        - domain: "vpn.${DOMAIN_OLD}"
          zone: ${DOMAIN_OLD}
          record: A
