---
# Namespace for Cloudflare DDNS
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-ddns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/instance: cloudflare-ddns
---
# ExternalSecret to fetch the Cloudflare API token from external secret store
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-cloudflare-api-token
  namespace: cloudflare-ddns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/instance: cloudflare-ddns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-api-token
  data:
    - secretKey: apiToken
      remoteRef:
        key: /CLOUDFLARE/API_TOKEN
---
# HelmRelease for Cloudflare DDNS updater
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-dyndns
  namespace: cloudflare-ddns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/instance: cloudflare-ddns
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflareddns
      version: 12.7.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: cozy-fluxcd
  valuesFrom:
    - kind: Secret
      name: cloudflare-api-token
      valuesKey: apiToken
      targetPath: cloudflareddns.api_token
  values:
    podAnnotations:
      reloader.stakater.com/match: cloudflare-api-token
    cloudflareddns:
      interval: 300 # seconds
      detect_mode: dig-whoami.cloudflare
      detect_override: dig-google.com
      log_level: 3
      host_zone_record:
        - domain: ${DOMAIN}
          zone: ${DOMAIN}
          record: A
        - domain: "vpn.${DOMAIN}"
          zone: ${DOMAIN}
          record: A
        - domain: "jellyfin.${DOMAIN}"
          zone: ${DOMAIN}
          record: A
        # These two below are for the old domain, to keep it working until DNS is fully switched over
        - domain: ${DOMAIN_OLD}
          zone: ${DOMAIN_OLD}
          record: A
        - domain: "vpn.${DOMAIN_OLD}"
          zone: ${DOMAIN_OLD}
          record: A
