apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-le-tls-cert
  namespace: tenant-root
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/allowed-namespaces: "media"
spec:
  dnsNames:
    - "*.${DOMAIN}"
    - "${DOMAIN}"
  secretName: wildcard-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
