# Kustomization for Readarr.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: cozy-fluxcd
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: cozy-fluxcd
  path: ./kubernetes/apps
  prune: true
  dependsOn:
    - name: bootstrap
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-secret
