---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# Kustomization for Apps.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: cozy-fluxcd
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: cozy-fluxcd
  path: ./kubernetes/apps
  prune: true
  dependsOn:
    - name: bootstrap
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-substitution
  wait: true
  healthChecks:
    # Ensure the flux-substitution secret is present.
    - apiVersion: v1
      kind: Secret
      name: flux-substitution
      namespace: cozy-fluxcd
    # Healthchecks for Cloudflared app.
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cloudflared
      namespace: cloudflared
    - apiVersion: v1
      kind: Secret
      name: cloudflared-cloudflare-tunnel-remote
      namespace: cloudflared
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: es-cloudflared-cloudflare-tunnel-remote
      namespace: cloudflared
    # Healthchecks for External-DNS app.
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-dns
      namespace: external-dns
    - apiVersion: v1
      kind: Secret
      name: cloudflare-api-token
      namespace: external-dns
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: es-cloudflare-api-token
      namespace: external-dns
