---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: components
  namespace: cozy-fluxcd
spec:
  interval: 10m
  timeout: 15m
  prune: true
  wait: true
  # point to the ESO install folder
  path: ./kubernetes/components
  sourceRef:
    kind: GitRepository
    name: cozy-fluxcd
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets
      namespace: external-secrets
