# Kustomization for shared sources.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: cozy-fluxcd
spec:
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: cozy-fluxcd
  path: ./kubernetes/sources
  prune: true
