# ResourceSet for deploying Cloudflared.
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: cloudflared
  namespace: cozy-fluxcd
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudflared

  resources:
    # Cloudflared namespace.
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: cloudflared
        labels:
          app.kubernetes.io/name: cloudflared

    # Cloudflared Helm repository.
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: cloudflare
        namespace: cozy-fluxcd
      spec:
        url: https://cloudflare.github.io/helm-charts
        interval: 1h

    # Cloudflared ExternalSecret.
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: es-cloudflared-cloudflare-tunnel-remote
        namespace: cloudflared
      spec:
        refreshInterval: 1h
        secretStoreRef:
          kind: ClusterSecretStore
          name: infisical
        target:
          name: cloudflared-cloudflare-tunnel-remote # This secret name is automatically fetched by the Cloudflared helm chart.
          creationPolicy: Owner
        data:
          - secretKey: tunnelToken
            remoteRef:
              key: /CLOUDFLARED/TUNNEL_TOKEN

    # Cloudflared helm release.
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: cloudflared
        namespace: cloudflared
      spec:
        interval: 10m
        chart:
          spec:
            chart: cloudflare-tunnel-remote
            version: "0.1.2"
            sourceRef:
              kind: HelmRepository
              name: cloudflare
              namespace: cozy-fluxcd
            interval: 10m
        values:
          podAnnotations:
            reloader.stakater.com/match: cloudflared-cloudflare-tunnel-remote
          replicaCount: 2
          image:
            tag: "2025.8.1"
            pullPolicy: IfNotPresent
        install:
          remediation:
            retries: 3
        upgrade:
          remediation:
            retries: 3
