---
# ResourceSet for deploying Cloudflared.
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: cloudflared
  namespace: cozy-fluxcd
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudflared
  decryption: true
  dependsOn:
    - apiVersion: v1
      kind: Secret
      name: flux-secret
      namespace: cozy-fluxcd
      ready: true
  resources:
    # Namespace for Cloudflared.
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: cloudflared
        labels:
          app.kubernetes.io/name: cloudflared

    # Source for Cloudflare Helm Repository.
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: cloudflare
        namespace: cozy-fluxcd
      spec:
        url: https://cloudflare.github.io/helm-charts
        interval: 1h

    # This secret is used to authenticate the Cloudflare Tunnel to the Cloudflare network.
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflared-cloudflare-tunnel-remote
        namespace: cloudflared
      type: Opaque
      stringData:
        tunnelToken: ${CLOUDFLARE_TUNNEL_TOKEN}

    # Cloudflared HelmRelease.
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: cloudflared
        namespace: cloudflared
      spec:
        interval: 10m
        chart:
          spec:
            chart: cloudflare-tunnel-remote
            version: "0.1.2"
            sourceRef:
              kind: HelmRepository
              name: cloudflare
              namespace: cozy-fluxcd
            interval: 10m
        values:
          podAnnotations:
            reloader.stakater.com/match: cloudflared-cloudflare-tunnel-remote
          replicaCount: 2
          image:
            tag: "2025.4.0"
            pullPolicy: IfNotPresent
