apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cozy-fluxcd
      interval: 10m
  values:
    podAnnotations:
      reloader.stakater.com/match: cloudflared-cloudflare-tunnel-remote
    replicaCount: 2
    image:
      tag: "2025.4.0"
      pullPolicy: IfNotPresent
