---
# ResourceSet for allowing Cozystack updates and mods - Flux takes ownership.
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: cozystack
  namespace: cozy-fluxcd
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: cozy-system
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cozystack
        namespace: cozy-system
      data:
        bundle-name: "paas-full"
        ipv4-pod-cidr: "10.244.0.0/16"
        ipv4-pod-gateway: "10.244.0.1"
        ipv4-svc-cidr: "10.96.0.0/16"
        ipv4-join-cidr: "100.64.0.0/16"
        root-host: ${DOMAIN}
        api-server-endpoint: https://${K8S_ENDPOINT_IP}:6443
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: cozystack
        namespace: cozy-fluxcd
      spec:
        interval: 10m
        path: .
        prune: true
        sourceRef:
          kind: GitRepository
          name: cozy-fluxcd
        dependsOn: []
        patches:
          - target:
              kind: Kustomization
            patch: |
              - op: replace
                path: /spec/sourceRef/url
                value: https://github.com/cozystack/cozystack/releases/download/v0.30.3/cozystack-installer.yaml
