---
# The external-secrets-operator has been installed as an optional feature of Cozystack.
# The following ResourceSet is used to deploy the necessary secret and ClusterSecretStore.
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: external-secrets-operator-setup
  namespace: cozy-fluxcd
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
spec:
  resources:
    # Flux SOPS/age secret with GitHub AppID, InstallationID, Organization, Repository and PrivateKey.
    - apiVersion: v1
      kind: Secret
      metadata:
        name: external-secrets-github-app
        namespace: ccozy-external-secrets-operator
      type: Opaque
      stringData:
        appID: ENC[AES256_GCM,data:igBQfkstgQ==,iv:0Bpl5Q3P+YE3Nvy7o1MOflwYa5jA+KEJlu7AlWbp5x4=,tag:nVUxD7RNrmh6wGDPc+6zcA==,type:str]
        installationID: ENC[AES256_GCM,data:edsPojAyOd4=,iv:L+4iZmyLWQk0usJMX3mwieiLHSxgl7r9kSzqzRvqR3U=,tag:p6cwkaT2KH2zXYr4vvK+dg==,type:str]
        organization: ENC[AES256_GCM,data:roTxxMgGtB9/,iv:WZ/d23fqrOKx5JAhIfSN+/ctX7Nm+NSBj2D+QdU6BSk=,tag:Mxkae8+vx5g/B54+jHl7Lg==,type:str]
        repository: ENC[AES256_GCM,data:b+k2VV6/DLE=,iv:/f3v8f2GsKatQg9vfKeBB6yv2e/fwVIppxw7LdWdxB4=,tag:rNc0qg22s2NptNeZ3ea3bg==,type:str]
        privateKey: ENC[AES256_GCM,data:5BLPgT7gBA/LX9uTaXpLJfmk4HM/vO5nzp4hzmm2+n8dTV5FHwXcsA6ImbO1UudSHFwTmEObMCl4HIs4rauQjh2ahk58aiTFKngnG15nIyC02yUgK0rPxJ/LhJlO4VdFQ9jfujHOGcrLzC+NrKekJfcqrjXEI1GdF+qt7cRt5OYFriggWq5eeNT+axRX0xQBBhCJxdS+WPPhF/iGuD0kUPuQEL1WecT8ZxGaH6lBG5zcE8Q9eyrizJMOtBzkLi21ocifTCHx3YlovkYuFoMmU5MhWj/jPNheZVWBhOr2xWh3xNP8fKeUpoi07b+l13a5eD5g8hXmXA0DXn4vksvwCw/zuzg2dMKJFbwfXaIvmfXK8h6GAL595uJdZNOSRaSduAHWYwSJxAo5kSBnZW6qLTK3QYZ4giWvcljrStucrNbgBm4cSRNiBxxmuJbHxlk0C1+ZdPxT2aMuXDaXckJPfKLBVp35J+p7jZW4lFfaZfSjJHQdhh2urrOaUL6WjNehj9QVO66mf5xfTxClYR33ChGwf/K/mefwznCK1mfztKbtODYFdVcvUH+5XZo908x7wtvP7/RpALa8yWIa6Z86g0QyRcSVSJKsXDP/I8NQOK4fFTy337bCMn7OgSKUVpZjam3WwFJFgJ7yJUK90aNsLpwEqrYtYCMHHIym+y/sJ6XtMeer1RNt+NNU7Hc2L6hV1Gwtl4d0QrNETH6cwmyxh7YCzej1XEda6oCYetWHsjF5Es3VdNYgo1MwayY4hboAkz7SKPpJm+SYPmBVwDGBMWYkHKBqx4KMv1g69i9IWaV6RvvlntQtUHpWRks+LKOlmY3zxPkj5KdcGsX8QX5gdHkds/UUSHDiDTxfr5AwR2ioFilwy5nfMd+kwHhm0EiixYTrktfS0W8QmrQAyGqLOGnbjpbm2vZdsMyR14bx8wePOPS+UvPewckVnvn3VHL7xZIiarhZwskjL3i2NtBmzGR8ZFu5hfR8sOMbKCpqDmJtZkASjGKwAmmwU7V2sP6WNAgoZKRjJbsnXmorL77nf9uiEDH8vF5zqcG5pwAxR28b9A+hxG3B5nu35b+W1/nJvAR60oJGYiOFNjv3hFTTIfdwVoBjCZT5bf6t4PBX0iaOPwVNsJrDbSNOD5AXeZs7K04VNeV1vuRpz/dVvHIwtUdKGqoceNQ/FUNz0F3g3Q1ZUT0XIZilMmK92O2cJagILDnPglTM5++niex6rrsz1ovmegvEMg7VgGqu+goeZWtIPfwdDg94/9WdX1oQYLulh46x90a8D8PPCe4rp++i38xxYnREwaTsYUgoXzN5sRftCLbBa9o57NeySqL4AV7N/zvJ+SoqRgeK3nYfrIYxL5QQMEGCV6N02LQjJqqWA0QQ8bbQEbtxoVCIDbc7Lo0i/B0TRD2g4Nj1yqyD5xcLPuiuRmlFhDQbrEaNkG/7huc0TzfxcUR0XRQuRPBlHOl4xrMayLHilEU5w5oPLSHg4HI11S09/4Mqh2ntPV06iuWTvrMDAYzJ0jPDjxFUAtR5EPj4qctRsG6coXoZ83D4Q3hVmPZnp3mMtj2EcOsX5Z45w+REgJ3dkn/kFYt45sL6Lrf7zumwopV1Hp83O1lgBE/4yE3PHQazm7BRjtwll1m3B9lPOA7BOyq90e9kk09750CnJrB3/93YseE1Q4Owh3ets6mHD1lH65meTCK7TJ0T9OVKoaxgVyOh7Bp8rrTU8F6k0A/TuYUTKklUo984mS7DX7bZ48aAfWn62A2DyIbqgxsjEDgsM1z47Cn0W2X9gC+At3EVe1eC7nerYG566lHInyzkakrEN1iAUET8boqpnC0gqzlU1HDXzy+UI8a3KsDF5yPlAlDx9EofZhJGM9Ylui8057HAEiWap5xrWAPBT3a5xceG0LIXBYLH1Pz6EwoGp7bOn1sFonP2VNIWHM9wnJkadoTuNVLRKcomLpJHLa5d3IMt1cglB65sTFt0Xd6X7lzXUSm8ihhSZ5dLQlGX7/CI5bc/b3HMrMEcoLkC+pgeXOlAQHjsWXWticuqXSz9jk/p/ErPPp8KRmesdEx8iUqepZ0j+df/5BDb49RrGYNSGMrAhKDDW6OIBlDuMnqihQndfdeW0Ly/QY8RLeF5kF8381hX8PzCVmv9k9HtvvuUUPnmSgHDqavaDdsYfRVFvmwM/eJmjHsIt1vejZi6w7bHV6+IErziYMsc6YnpLSdYj19aSwmUhQ==,iv:LZrsCmeyZ0yRDJiRd9VZ499iqQ6gM5H2ffrCnPOPaaI=,tag:ZHNLqd90QmzNckaRb4E/3w==,type:str]
      sops:
        age:
          - recipient: age1mlzqnslh2nrf3m4ey2afp7rqq8wtmck8t3f3xwkarqpap7e9gvtshwgx2e
            enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ0FpMU1nNVV3V01UYzNi
              RlpUUWUvMmJTNUxvRmRDN2dXdW03RlRYalFzClI4aXZLLzVSM3VVbnlZTTVFcTZF
              RGxvaGRYSkFTUHdFRGNVMS9LZkdzK3MKLS0tIG5wRkNuQStBWkI4UDZ3aXFybG9l
              RXhOclQ2T1pyMm9BNTFPVU04b29RMGcKWu7KMkTEEcsVksPfDn+1J6jrY+e6YRqV
              DdCNA/+4kfzmkKvkkMNSeCVtZ1iehhIJLfBL8G/8mhnRFXsS+lpH9g==
              -----END AGE ENCRYPTED FILE-----
        lastmodified: "2025-04-20T13:35:19Z"
        mac: ENC[AES256_GCM,data:mBcKC6oIH/S1KPAbBJTCXcEcvLDQIPs7T50sJGzW2W3oAzWw+ECLec29aaqh3PKS93GgvnbecFf3nZau+TiLoOR5r7yEVFIazAvTly551gkZN+WdQ6haUerzR7rofkLrj8I0aeN3OBzAomn562hWPhd6kOiWecukjxiyZbSW6ko=,iv:gLSLosVbUjfYr8fjpcB30JJ3Fgy6AygKcDchAO5peCo=,tag:c91GFbY4+jQV9FabPMTe+A==,type:str]
        encrypted_regex: ^(data|stringData)$
        version: 3.10.2

    # ClusterSecretStore for GitHub with AppID, InstallationID, Organization, Repository and PrivateKey.
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      metadata:
        name: github
      spec:
        provider:
          github:
            appID:
              valueFrom:
                secretKeyRef:
                  name: external-secrets-github-app
                  key: appID
                  namespace: cozy-external-secrets-operator
            installationID:
              valueFrom:
                secretKeyRef:
                  name: external-secrets-github-app
                  key: installationID
                  namespace: cozy-external-secrets-operator
            organization:
              valueFrom:
                secretKeyRef:
                  name: external-secrets-github-app
                  key: organization
                  namespace: cozy-external-secrets-operator
            repository:
              valueFrom:
                secretKeyRef:
                  name: external-secrets-github-app
                  key: repository
                  namespace: cozy-external-secrets-operator
            auth:
              privateKey:
                name: external-secrets-github-app
                key: privateKey
                namespace: cozy-external-secrets-operator
