---
# ResourceSet for allowing Cozystack updates and mods - Flux takes ownership.
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: flux-secrets
  namespace: cozy-fluxcd
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    # All variables for apps in the cluster, encrypted with Mozilla SOPS/age.
    # This secret is deployed to the cluster using Kustomization, on deploy it gets decrypted.
    # The decrypted values are then available for the Flux system to use for variable substitution into namespaced secrets.
    - apiVersion: v1
      kind: Secret
      metadata:
        name: variables
        namespace: cozy-fluxcd
      type: Opaque
      stringData:
        DOMAIN: ENC[AES256_GCM,data:z+o76nfdrNg=,iv:KzpQyt5GQHRNyvHNBu1wJpkMi5Llele6QMmPNWxZD9A=,tag:tvP4JZki551UsgPaeUoJWA==,type:str]
        TZ: ENC[AES256_GCM,data:c8EVbBDw+ojaRRzcO70CbA==,iv:GSwPBqlwv/l3c+RAOjnfkg3Olqz5zOrh57i5JFltUGI=,tag:XlN7FcXRmNOE/DGlavkvLA==,type:str]
        PG_APPUSER_USERNAME: ENC[AES256_GCM,data:vjbB,iv:dnDjvRa+OdzrV2/A94TBbR02UsvfGObfxvsx56ilBa8=,tag:vRKgYiAvfVpH66HD79vJrQ==,type:str]
        PG_APPUSER_PASSWORD: ENC[AES256_GCM,data:EnkJ+gr4kh6QQvEoDeKDn03azXk=,iv:y9Sp+yxcIbVcXfXYJfUoLZgctOv/J5Ow5sH/uMK/Mdk=,tag:GsdEmPeageRLCJcSZfT/9w==,type:str]
        PG_POSTGRESUSER_USERNAME: ENC[AES256_GCM,data:ViPqFjnkNV8=,iv:mO4jFho+u+sU65k75t28vfjjI9IeXxnAxWNuPUR8+o4=,tag:sVAu7tYInNAq6iLk8ghOdw==,type:str]
        PG_POSTGRESUSER_PASSWORD: ENC[AES256_GCM,data:b/qj0MhhrZPeP4+t3IYTO9I=,iv:2gBc5MloEblRzlDq7mrHn61tPf8roff3L2pArmeCbLg=,tag:8B27n3kD9yIuWGj6qRw63A==,type:str]
        PG_RW_HOST: ENC[AES256_GCM,data:po6s7Zo+17PAmCVWPmVtqxLofClUgHp0o4A2A/GLExxlCNfrQxo=,iv:i2l+U26RANglrJuUgBaAPkNqWfychAd/rW8KjBou+0I=,tag:PMBeaKQekFBYRSkdbG3HEg==,type:str]
        PG_PORT: ENC[AES256_GCM,data:i0d//g==,iv:Nc9oZ4ZWw78qc1LiaXaSg7kJz4lmWRtQ0D50AnVvB+E=,tag:9Nf7T68LO7NngGDIzUlAPQ==,type:str]
        QBT_IP: ENC[AES256_GCM,data:cVX5oqw4I68TorDnwztJ,iv:1iN/HUOBi3R10ndkkG26dCm3Cdojx+LH0U9cZwP3zX0=,tag:MgTlppyHfuCcAZqQytOJrA==,type:str]
        GLUETUN_PUBLICIP_API: ENC[AES256_GCM,data:iGYAAimiVDsdfQ==,iv:1Sd8wFkbg2vLP8HBtYSBo8FYhlA7FTc767XH5sRvn1g=,tag:j3shpXf1mdHd83XIsrZs2Q==,type:str]
        GLUETUN_VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:HDWQvKx8fQ==,iv:ksg/wnkgdBBv6IzRBFkRFpoCnkYZlUVpL1YUxkyXVoo=,tag:fYJ0jcnBFHuzP3mXJinaeg==,type:str]
        GLUETUN_VPN_TYPE: ENC[AES256_GCM,data:ogAE1Cd3OyvQ,iv:Af4zlzt0ejNcUWZhz2Q6GVk/4FJaWkPBkJboJ+sDNPs=,tag:tMJwuddCAQPTY8wlZyn5dQ==,type:str]
        GLUETUN_SERVER_COUNTRIES: ENC[AES256_GCM,data:qqA9a0QMffwcANd22E5pupzB9zGJtg==,iv:/TeqjyK2jmx0pLN5jeY6iB63KtiWSU9N5RYeRFRBhSo=,tag:LNwzztHfkWsyG9iChJNonA==,type:str]
        GLUETUN_DOT_PROVIDERS: ENC[AES256_GCM,data:glWJ/vw=,iv:/ug2WFgerwsR6bsQgQk6E7vo9eBYT7YUW+b9FpjbVM0=,tag:0aoNMMo60LUhEw0YhJ31ag==,type:str]
        NORDVPN_WG_PRIVATE_KEY: ENC[AES256_GCM,data:Ti/JOs5nUcCJHBTLD/55x03tZsU940VNSmhoElaRH6T37E9w0kd26GCc/ss=,iv:rumgw7SyNKqfNn1dl+ie4q6N9TidPGIQ8Y7coqdMKjk=,tag:bt7ntxQ/9h8SR781H04WHw==,type:str]
        PLEX_API_TOKEN: ENC[AES256_GCM,data:5XkwzKBCqVWAPVzZAuVYMBfXrzo=,iv:xpA7G3WAakGd0Z+xYl+Sx525855DKNBoIsdyd6giwKY=,tag:ujPDN3rYccTXgVm9CNHLBg==,type:str]
        PLEX_IP: ENC[AES256_GCM,data:9w4ZsM54QN2GMQ7AvCmD,iv:QF9cceN4/VbAm8P08moIWxQ+2dq/vjA+14EDAALJNrs=,tag:g1cT2zCZTdwo+bK7ZftSlA==,type:str]
        CLOUDFLARE_TUNNEL_TARGET: ENC[AES256_GCM,data:xAVVWDBcPN/nbUrcKti908zmmMogQvPi5OWxbuB6rtfVBsTDMM57R2PUOAYGvdkZf1iRWSg=,iv:UvvXDFM2xYFvYOVizIk8W+wxIMFbX25wvVEb8zVlY3s=,tag:Ft+FSQzgHa9gHQW6NDT4Ww==,type:str]
        CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:RVuytKefL/I+TG0ZjsVQD78blIX0ae+zrUAixKF4F/9G38uOE3TSN0wACSqVhxTodJIYg2Mrey8eBYu1GYRoGiOz4smdKPEzE/8wk9k3NOkiPJQaPsqTMiv6hUUl8vmz4jpCRfpFt+dcihgyR+JJgv6VzGuMVvuVbx97kQMC5WlXF7rS2Px0blKOD6JnGCAbD1hKOrOugss/jhxwZFZ2zYikk6verZ/2jjzEmB8YG8gB/GTjFMajEQ==,iv:1DMrf1jFAsT615ldh6mnJt6TfKvV3dOk2hrK1uaBeVo=,tag:hMQ0GfayxztFUfe/wulnYA==,type:str]
        CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:tP7C8FaGpSnLa8HjIBmznD0433fVckDjGuzKrERGEU9bPMfFB9FIQw==,iv:wJWlj1yUx+U1ETYTSWpzLI9YwrOM7dd7YJnS8umGXNU=,tag:b783Q17F2C5DGAd6cJ+r0w==,type:str]
        ACME_EMAIL: ENC[AES256_GCM,data:Z3PxZHCoSJfBQqoVYAe48JRQ4ubkxB3bQkcF+w==,iv:tawGJwEbNTDfO++a9Nt5kR+tc5+PNmBKHT7mWX8POYE=,tag:GkIIyjD0whBsNg4BFGoaJQ==,type:str]
        FILESERVER_NFS_HOST: ENC[AES256_GCM,data:+uprWSSsaIr9rMACu7c=,iv:vjN0BOvEAHfZYyAqmkwr+OdITJlmxL8O5uqs0skhli0=,tag:h0m8B68Arm3lzWODwr2n1Q==,type:str]
        FILESERVER_SHARE_MEDIA_NFS_PATH: ENC[AES256_GCM,data:XIDx7IVkoUndYgs7vJ54,iv:MaNuSGtO0RuvECBHk4VfBuNwaw2STMz5r+m56Ag4Cxo=,tag:i55DSS05qaeu/B7DTDRgBA==,type:str]
        METALLB_IP_ADDRESS_POOL: ENC[AES256_GCM,data:/uczjWDMBom5xIVzy0V/i/ShNGshqTAmWKVpmF519g==,iv:H+QaD1iyYJfivx8q0ewWzApFrkE3p2NdiqaMiGX3WC8=,tag:EfL0BfkW/JcCJH4nT0dP9Q==,type:str]
      sops:
        age:
          - recipient: age1mlzqnslh2nrf3m4ey2afp7rqq8wtmck8t3f3xwkarqpap7e9gvtshwgx2e
            enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNREFMOTREU2VSMytGMUNt
              Uk9ReTRaK2l2MGNPaUUvRVVJbXU2dDJlTWswCkFlNWRSU1hUTlFGak5JZXNQZ2ps
              ZWg1MS9RdGtqRGdyK2hJaXh5ck00SWsKLS0tIGc1RG0zN0xHUHU1NHdGWjIzNEhl
              Q1BwVGU0RUduS1dKSjlhZm9ZSnhNRzQKv6yBqYLuZUiaveMepWJ1MLZCK+S9nWqZ
              mEeII6CYoX5SrT/sm8U6E0FmmxJyxGujKnfRobttXk5cTr0Rq61/3A==
              -----END AGE ENCRYPTED FILE-----
        lastmodified: "2025-04-23T12:31:35Z"
        mac: ENC[AES256_GCM,data:q6VmFsMoXrEI6CjJooWbt4WT+Y9W+T1MhlVB5J2i66epNYjTAXZAPojhYke83Yo/bRWgycRTXpC/IFyzV5AIUZdgjKoIzp1QHBDdILWLXHP2wlLl5KaQU7XwmmR9DiQCCOWCnIDPlu4u3tTlRiIhmV9RjKdCKAyUJ2hcMOdc73w=,iv:/AP5398BIiiHH8W2rEko0fBkM9danSYP5zQWN4uzUWA=,tag:buseud6YKqNxzLZMz+tagQ==,type:str]
        encrypted_regex: ^(data|stringData)$
        version: 3.10.2
