---
# ResourceSet for allowing Cozystack updates and mods - Flux takes ownership.
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: flux-secrets
  namespace: cozy-fluxcd
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    # All variables for apps in the cluster, encrypted with Mozilla SOPS/age.
    # This secret is deployed to the cluster using Kustomization, on deploy it gets decrypted.
    # The decrypted values are then available for the Flux system to use for variable substitution into namespaced secrets.
    - apiVersion: v1
      kind: Secret
      metadata:
        name: flux-secrets-secret
        namespace: cozy-fluxcd
      type: Opaque
      stringData:
        DOMAIN: ENC[AES256_GCM,data:Rb8vcGvD0wo=,iv:1msHD7jZxAN/AkxXCq4fy1b7JMOv9rkJKmtKuBUh1tw=,tag:feOJo5bFZmDimK/PetXMVQ==,type:str]
        TZ: ENC[AES256_GCM,data:CAFBajbrBFZywWUN1tgSSQ==,iv:R2Eokxwmmuo4BdLJnQ2hr29cwoH2BS7PtmbUtBsYa2g=,tag:qQu3TWFA0LYe7xBS5zEgTA==,type:str]
        K8S_ENDPOINT_IP: ENC[AES256_GCM,data:xjqhpWvjkWXezXkBlqk=,iv:3kUlx1XerlmecLyfqTR6iLbvMzg09huQ5V2nGJ2+o1w=,tag:yxEhgc5GbMAs2c/KPpuTZg==,type:str]
        PG_APPUSER_USERNAME: ENC[AES256_GCM,data:RfEQ,iv:2rGCIztkNk5r6yjruHLHzqESyjzyoNvbCTpgJiM3rk8=,tag:8WE+Bq/uYmMeQoFbPAoITQ==,type:str]
        PG_APPUSER_PASSWORD: ENC[AES256_GCM,data:ixYgv739sXQnqpOxJoUEGqDIioE=,iv:clxv2fsR8lATd6PAij6RRevHuMQ5617WH9YnuAgtW1M=,tag:ryRmF73IkR59vEkhjlEbxg==,type:str]
        PG_POSTGRESUSER_USERNAME: ENC[AES256_GCM,data:jUsiHTEXTwM=,iv:nJFtt1HVHym63mzRkk+npwg4WXGzreKUanYQgHUXsmk=,tag:ZKZ5sbVCFgPOJSNknPshgA==,type:str]
        PG_POSTGRESUSER_PASSWORD: ENC[AES256_GCM,data:Zw+Y9LALWA/CkjM9DJwJK5w=,iv:hxNuWo3luvIqQP3/JmAIKr6PvAhvNLdCglM/yzgkyRQ=,tag:O6i5z1ZG2bKmKWESJcabgg==,type:str]
        PG_RW_HOST: ENC[AES256_GCM,data:ClCfPMHRp+3e9ZLGN7Akg/k9dxFCjfk1UzlABCdxNTd//nUnLM4=,iv:vpFJKrddzHtVt5XYHAIJFuN3mwUk2Y5Ka4nTOZ7hRNk=,tag:y/c72r7OcoByU0Cox4fuDQ==,type:str]
        PG_PORT: ENC[AES256_GCM,data:IDMUQA==,iv:4rGTUDJ7gSlpO3G94xPkv2Jre1G8eYurzZI5jthHR5I=,tag:FNUadV7MlgK9fuVLwcO6Pw==,type:str]
        QBT_IP: ENC[AES256_GCM,data:txyg8rZ6mAy17VzOkk4Q,iv:a9rWXyXcVJ70U68G60/BhsBwMHsXAzLdo09QjKKZbu4=,tag:9/O5e7HDUaLfp4oRoYDBNg==,type:str]
        GLUETUN_PUBLICIP_API: ENC[AES256_GCM,data:Sh+qToAJsrLUMg==,iv:XJWVK5WSzpKX4rYkQwIZzZvd5dNRMVeQsYOLwrzoQW4=,tag:lQRwgw7Ud6+fZOa5hyfopg==,type:str]
        GLUETUN_VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:IJNGAkS36Q==,iv:KheWY1n6244uWzpvK5uHkYXkK74l2Askp9q8U63rw3g=,tag:8VuKeB0e7jb9brAa9PrSgw==,type:str]
        GLUETUN_VPN_TYPE: ENC[AES256_GCM,data:227J9ft6Xfze,iv:+xmSkQJ/iL2J7cCAjawBjGMr/2GDU9uyKRGE9YGGWvo=,tag:kh8fO3xDZR5qXnmUOyoF5Q==,type:str]
        GLUETUN_SERVER_COUNTRIES: ENC[AES256_GCM,data:0hUFeyBaZsbS9RXJ9DzJS5P+Gq2whA==,iv:uPz5jdZyVO99Oe1rqrDDOtvwmtaC28rMP3F4k4uG8sc=,tag:Xdy6hfdlACmKpqUQKGDnrA==,type:str]
        GLUETUN_DOT_PROVIDERS: ENC[AES256_GCM,data:Eywwo1mNM2ZU/XZNgDKHrlOfkvQjwWs=,iv:qVLnM5P2AR8QLTiKxwt4VK94MbTMGuR0aaXsWXKFKGI=,tag:yPbT40LHJc1pJJF9IgGPkQ==,type:str]
        NORDVPN_WG_PRIVATE_KEY: ENC[AES256_GCM,data:tBU1lDnVnwDXWGu9njUi2w3h3APgC7N/It3HV54MuRJ5nR1NlRo2kyfhhaw=,iv:FfnuVh5brJ8NV7qbXZeCNxL9ige11CnhUj4xbpLCwTE=,tag:N0CIWR8Yw4yGpbCDl+lAbA==,type:str]
        PLEX_API_TOKEN: ENC[AES256_GCM,data:guvgkU6J9FVT61WJmLo5zZpIHBc=,iv:66BPTDrF4Rdi1sFWPGuwB97S7TKbL623Iru/+FhwPjs=,tag:qFKPcZFYfFnNidZXdXu2+w==,type:str]
        PLEX_IP: ENC[AES256_GCM,data:AQK1DNPZCTsdmBnNNTeZ,iv:ApbzhQBVSubpRuSqQKL8PF9C8pwYCS87u0eRwUts2Ro=,tag:n8tRjizO6LhzV6Wqg2Cb8g==,type:str]
        CLOUDFLARE_TUNNEL_TARGET: ENC[AES256_GCM,data:CKuaAq3HqBca4e40H6FVc0YecXwnDgNKLFGn6bxETTTE4YSL6nQGhb5sev7PyWhI9J5uG2Y=,iv:d//VfOQ/ZaZRbjhuZQNjzD0zCOShBoUXaKgd3oXbti0=,tag:nySaJFrfcCcPtbEOij56nQ==,type:str]
        CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:aAXhSS9A+pIVA/QaZ8geDLHWv71yRHEQ/8Lp/orFV/Z8tE7Gz5+a8itmJqTjatJCQGRmdNNrQ2XjJsMsUFERwEO6esjwyWGw/4C1yb4KG6RYGSPxw0CwpQW17G7dk+dHTqIzK9MP1yZWFu24mqfiy9GZ6YuZY+JdQLKB5ofvNWACgf1L1BflC7AE01OR3aRV60HSXo9FKctyNmNHySeRXB8LWg1+b3D5QqL49+YuV8XnHiwd1w5BLA==,iv:iG5GUrXIGGFAES+SnqTZSvuVE/wAxLaZ0WJTjB11/fU=,tag:mHnOQJn6mSGgvUKFvetx3g==,type:str]
        CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:uUWdFfqrjtAz7L6NOhlQa00krw2yrPeBsa4LHwK9pmiLVSWN0qslAg==,iv:pV9sUbq6cuJ6MmUP4789xxiSfhoiwSzD4SLVYiw/7aA=,tag:vF/WOf/C6i76c8MTCoRLYg==,type:str]
        ACME_EMAIL: ENC[AES256_GCM,data:EnLHgbuJM0bmekd4zPOakieMJjFdZ7S35sIjvg==,iv:T7aB0YTTiNaagT7XCftM3OKntiUs4qkuYSYxflXXk6g=,tag:a+iSJlvC54jObbBemMXNYw==,type:str]
        FILESERVER_NFS_HOST: ENC[AES256_GCM,data:CJJ9D+qVl8X9wLpcmb0=,iv:wKPc363y9JlcIhzWCeILHtL8ERM4A9iPUMra6pG6Q60=,tag:GOueG4msEYqZD74fr48J9Q==,type:str]
        FILESERVER_SHARE_MEDIA_NFS_PATH: ENC[AES256_GCM,data:kZ+d0w+PzdlV0ZkhrVSJ,iv:mGCEQ6PRX1e0HDhKSDiv5JoJ6IbaARH+O70AvjVuHSA=,tag:eW/852uBGgadEF9T9Yj4hg==,type:str]
        METALLB_IP_ADDRESS_POOL: ENC[AES256_GCM,data:C8jKxhJf0uHKlHy7Jy2rH9dVfupzcYatb1jqk/9hEw==,iv:+vIqIDyV2piFm2yptLsjw6J4aNvat5k9YHxiSyOFji4=,tag:7+hEenpRRIET+N5iTDXj+A==,type:str]
      sops:
        age:
          - recipient: age1mlzqnslh2nrf3m4ey2afp7rqq8wtmck8t3f3xwkarqpap7e9gvtshwgx2e
            enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWSsrbWxHOXpubDVPSG1h
              aXdKRVpRTVE3NzlCRnhiVkNZNlVjRWFjclZJCmNhcDROTXhCRlROczloWVIzendm
              NU5QZXlJQXczSTlJY2laNklvbEVIV0kKLS0tIEdrUitVSXY2bmIvY2pYTkp6TkVX
              NTdRR0pnc0tyeHNpakpPRjdVMW02SEkKAiDEGifnOKS4bVBDG+te8huVh6jUDWSW
              QKXCkZDXOAk+0xk25vTp3n/74uWbzAKE+yMj+K/levuFjtIaNztHtw==
              -----END AGE ENCRYPTED FILE-----
        lastmodified: "2025-04-23T14:20:38Z"
        mac: ENC[AES256_GCM,data:O6FTTVpuVdEBUJErKTDUHaUD88P8Zucjib7h6jmg1LYkZ661RfrTcDXjeBoksGdT9DOjUx17PvuLupyi/EDnpWvAbR4tc4dBjKsrnBluNYI747/prIofvLgz4+eYgDx8bXqmXEr0VljEaQqYfpvohdbkmYpXC0A1GoCwdC8rGeY=,iv:q9ADfVjZAhqO5j/zJvS7jzTyqHYcmxTl4+eaoc8Riag=,tag:3sIFBMgYyAY3KtZ2CXCPrw==,type:str]
        encrypted_regex: ^(data|stringData)$
        version: 3.10.2
