---
# App user credentials for the initial DB owner
# yaml-language-server: $schema=https://raw.githubusercontent.com/external-secrets/kubernetes-external-secrets/main/deploy/crds/external-secrets.io_externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: se-blocky-db-creds
  namespace: blocky
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: blocky-db-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /BLOCKY/CNPG-USERNAME
    - secretKey: password
      remoteRef:
        key: /BLOCKY/CNPG-PASSWORD
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/config/crd/bases/postgresql.cnpg.io_clusters.yaml
# CloudNativePG Cluster — creates a "blocky" database owned by user "blocky"
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: blocky-db
  namespace: blocky
spec:
  instances: 1

  # Use the operator's supported default image, or pin a version explicitly:
  # imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  storage:
    # Set your storageClass if needed (commented out to use cluster default)
    # storageClass: longhorn
    size: 5Gi

  # OPTIONAL: if you want postgres superuser access with a known password, set:
  # enableSuperuserAccess: true
  # superuserSecret:
  #   name: blocky-db-superuser

  bootstrap:
    initdb:
      database: blocky # database to create
      owner: blocky # owner of that database
      secret:
        name: blocky-db-creds # takes username/password from this Secret

  monitoring:
    enabled: true
